// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox_task.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOutboxTask = `-- name: CreateOutboxTask :one
INSERT INTO outbox_tasks (
    id,
    task_type,
    queue,
    payload,
    max_retry,
    process_at,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'pending'
) RETURNING id, task_type, queue, payload, max_retry, attempts, process_at, status, last_error, dispatched_at, created_at, updated_at
`

type CreateOutboxTaskParams struct {
	ID        uuid.UUID `json:"id"`
	TaskType  string    `json:"task_type"`
	Queue     string    `json:"queue"`
	Payload   string    `json:"payload"`
	MaxRetry  int32     `json:"max_retry"`
	ProcessAt time.Time `json:"process_at"`
}

func (q *Queries) CreateOutboxTask(ctx context.Context, arg CreateOutboxTaskParams) (OutboxTask, error) {
	row := q.db.QueryRowContext(ctx, createOutboxTask,
		arg.ID,
		arg.TaskType,
		arg.Queue,
		arg.Payload,
		arg.MaxRetry,
		arg.ProcessAt,
	)
	var i OutboxTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Queue,
		&i.Payload,
		&i.MaxRetry,
		&i.Attempts,
		&i.ProcessAt,
		&i.Status,
		&i.LastError,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxTask = `-- name: GetOutboxTask :one
SELECT id, task_type, queue, payload, max_retry, attempts, process_at, status, last_error, dispatched_at, created_at, updated_at FROM outbox_tasks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOutboxTask(ctx context.Context, id uuid.UUID) (OutboxTask, error) {
	row := q.db.QueryRowContext(ctx, getOutboxTask, id)
	var i OutboxTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Queue,
		&i.Payload,
		&i.MaxRetry,
		&i.Attempts,
		&i.ProcessAt,
		&i.Status,
		&i.LastError,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOutboxTasks = `-- name: ListPendingOutboxTasks :many
SELECT id, task_type, queue, payload, max_retry, attempts, process_at, status, last_error, dispatched_at, created_at, updated_at FROM outbox_tasks
WHERE status = 'pending'
  AND process_at <= now()
ORDER BY process_at, created_at
LIMIT $1
`

func (q *Queries) ListPendingOutboxTasks(ctx context.Context, limit int32) ([]OutboxTask, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOutboxTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxTask{}
	for rows.Next() {
		var i OutboxTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Queue,
			&i.Payload,
			&i.MaxRetry,
			&i.Attempts,
			&i.ProcessAt,
			&i.Status,
			&i.LastError,
			&i.DispatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxTaskDispatched = `-- name: MarkOutboxTaskDispatched :one
UPDATE outbox_tasks
SET
    status = 'dispatched',
    dispatched_at = now(),
    last_error = '',
    updated_at = now()
WHERE id = $1
RETURNING id, task_type, queue, payload, max_retry, attempts, process_at, status, last_error, dispatched_at, created_at, updated_at
`

func (q *Queries) MarkOutboxTaskDispatched(ctx context.Context, id uuid.UUID) (OutboxTask, error) {
	row := q.db.QueryRowContext(ctx, markOutboxTaskDispatched, id)
	var i OutboxTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Queue,
		&i.Payload,
		&i.MaxRetry,
		&i.Attempts,
		&i.ProcessAt,
		&i.Status,
		&i.LastError,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxTaskFailed = `-- name: MarkOutboxTaskFailed :one
UPDATE outbox_tasks
SET
    attempts = attempts + 1,
    last_error = $2,
    process_at = $3,
    status = CASE
        WHEN attempts + 1 >= max_retry THEN 'failed'
        ELSE 'pending'
    END,
    updated_at = now()
WHERE id = $1
RETURNING id, task_type, queue, payload, max_retry, attempts, process_at, status, last_error, dispatched_at, created_at, updated_at
`

type MarkOutboxTaskFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
	ProcessAt time.Time `json:"process_at"`
}

func (q *Queries) MarkOutboxTaskFailed(ctx context.Context, arg MarkOutboxTaskFailedParams) (OutboxTask, error) {
	row := q.db.QueryRowContext(ctx, markOutboxTaskFailed, arg.ID, arg.LastError, arg.ProcessAt)
	var i OutboxTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Queue,
		&i.Payload,
		&i.MaxRetry,
		&i.Attempts,
		&i.ProcessAt,
		&i.Status,
		&i.LastError,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
