// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc_create_transfer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int64                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int64                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_rpc_create_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_rpc_create_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetFromAccountId() int64 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetToAccountId() int64 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *CreateTransferRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransferRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *TransferTxResult      `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_rpc_create_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_create_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_rpc_create_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferResponse) GetResult() *TransferTxResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_rpc_create_transfer_proto protoreflect.FileDescriptor

const file_rpc_create_transfer_proto_rawDesc = "" +
	"\n" +
	"\x19rpc_create_transfer.proto\x12\x02pb\x1a\x0etransfer.proto\"\x97\x01\n" +
	"\x15CreateTransferRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x03R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x03R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"F\n" +
	"\x16CreateTransferResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\v2\x14.pb.TransferTxResultR\x06resultB\"Z github.com/AJackTi/simplebank/pbb\x06proto3"

var (
	file_rpc_create_transfer_proto_rawDescOnce sync.Once
	file_rpc_create_transfer_proto_rawDescData []byte
)

func file_rpc_create_transfer_proto_rawDescGZIP() []byte {
	file_rpc_create_transfer_proto_rawDescOnce.Do(func() {
		file_rpc_create_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_create_transfer_proto_rawDesc), len(file_rpc_create_transfer_proto_rawDesc)))
	})
	return file_rpc_create_transfer_proto_rawDescData
}

var file_rpc_create_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_create_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil),  // 0: pb.CreateTransferRequest
	(*CreateTransferResponse)(nil), // 1: pb.CreateTransferResponse
	(*TransferTxResult)(nil),       // 2: pb.TransferTxResult
}
var file_rpc_create_transfer_proto_depIdxs = []int32{
	2, // 0: pb.CreateTransferResponse.result:type_name -> pb.TransferTxResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_create_transfer_proto_init() }
func file_rpc_create_transfer_proto_init() {
	if File_rpc_create_transfer_proto != nil {
		return
	}
	file_transfer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_create_transfer_proto_rawDesc), len(file_rpc_create_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_create_transfer_proto_goTypes,
		DependencyIndexes: file_rpc_create_transfer_proto_depIdxs,
		MessageInfos:      file_rpc_create_transfer_proto_msgTypes,
	}.Build()
	File_rpc_create_transfer_proto = out.File
	file_rpc_create_transfer_proto_goTypes = nil
	file_rpc_create_transfer_proto_depIdxs = nil
}
