// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc_list_accounts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        int32                  `protobuf:"varint,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_rpc_list_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_list_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *ListAccountsRequest) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *ListAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_rpc_list_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_list_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

var File_rpc_list_accounts_proto protoreflect.FileDescriptor

const file_rpc_list_accounts_proto_rawDesc = "" +
	"\n" +
	"\x17rpc_list_accounts.proto\x12\x02pb\x1a\raccount.proto\"K\n" +
	"\x13ListAccountsRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\x05R\x06pageId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"?\n" +
	"\x14ListAccountsResponse\x12'\n" +
	"\baccounts\x18\x01 \x03(\v2\v.pb.AccountR\baccountsB\"Z github.com/AJackTi/simplebank/pbb\x06proto3"

var (
	file_rpc_list_accounts_proto_rawDescOnce sync.Once
	file_rpc_list_accounts_proto_rawDescData []byte
)

func file_rpc_list_accounts_proto_rawDescGZIP() []byte {
	file_rpc_list_accounts_proto_rawDescOnce.Do(func() {
		file_rpc_list_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_list_accounts_proto_rawDesc), len(file_rpc_list_accounts_proto_rawDesc)))
	})
	return file_rpc_list_accounts_proto_rawDescData
}

var file_rpc_list_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_accounts_proto_goTypes = []any{
	(*ListAccountsRequest)(nil),  // 0: pb.ListAccountsRequest
	(*ListAccountsResponse)(nil), // 1: pb.ListAccountsResponse
	(*Account)(nil),              // 2: pb.Account
}
var file_rpc_list_accounts_proto_depIdxs = []int32{
	2, // 0: pb.ListAccountsResponse.accounts:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_list_accounts_proto_init() }
func file_rpc_list_accounts_proto_init() {
	if File_rpc_list_accounts_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_list_accounts_proto_rawDesc), len(file_rpc_list_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_list_accounts_proto_goTypes,
		DependencyIndexes: file_rpc_list_accounts_proto_depIdxs,
		MessageInfos:      file_rpc_list_accounts_proto_msgTypes,
	}.Build()
	File_rpc_list_accounts_proto = out.File
	file_rpc_list_accounts_proto_goTypes = nil
	file_rpc_list_accounts_proto_depIdxs = nil
}
