// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc_get_account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_rpc_get_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_rpc_get_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_rpc_get_account_proto protoreflect.FileDescriptor

const file_rpc_get_account_proto_rawDesc = "" +
	"\n" +
	"\x15rpc_get_account.proto\x12\x02pb\x1a\raccount.proto\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x12GetAccountResponse\x12%\n" +
	"\aaccount\x18\x01 \x01(\v2\v.pb.AccountR\aaccountB\"Z github.com/AJackTi/simplebank/pbb\x06proto3"

var (
	file_rpc_get_account_proto_rawDescOnce sync.Once
	file_rpc_get_account_proto_rawDescData []byte
)

func file_rpc_get_account_proto_rawDescGZIP() []byte {
	file_rpc_get_account_proto_rawDescOnce.Do(func() {
		file_rpc_get_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_account_proto_rawDesc), len(file_rpc_get_account_proto_rawDesc)))
	})
	return file_rpc_get_account_proto_rawDescData
}

var file_rpc_get_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_account_proto_goTypes = []any{
	(*GetAccountRequest)(nil),  // 0: pb.GetAccountRequest
	(*GetAccountResponse)(nil), // 1: pb.GetAccountResponse
	(*Account)(nil),            // 2: pb.Account
}
var file_rpc_get_account_proto_depIdxs = []int32{
	2, // 0: pb.GetAccountResponse.account:type_name -> pb.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_account_proto_init() }
func file_rpc_get_account_proto_init() {
	if File_rpc_get_account_proto != nil {
		return
	}
	file_account_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_account_proto_rawDesc), len(file_rpc_get_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_account_proto_goTypes,
		DependencyIndexes: file_rpc_get_account_proto_depIdxs,
		MessageInfos:      file_rpc_get_account_proto_msgTypes,
	}.Build()
	File_rpc_get_account_proto = out.File
	file_rpc_get_account_proto_goTypes = nil
	file_rpc_get_account_proto_depIdxs = nil
}
