// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: service_simple_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x14rpc_login_user.proto\x1a\x18rpc_create_account.proto\x1a\x15rpc_get_account.proto\x1a\x17rpc_list_accounts.proto\x1a\x19rpc_create_transfer.proto\x1a\x1crpc_renew_access_token.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xbd\t\n" +
	"\n" +
	"SimpleBank\x12\x8e\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"Q\x92A4\x12\x0fCreate new user\x1a!Use this API to create a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\x84\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"G\x92A*\x12\vUpdate user\x1a\x1bUse this API to update user\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\xa3\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"i\x92AM\x12\n" +
	"Login user\x1a?Use this API to login user and get access token & refresh token\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x93\x01\n" +
	"\rCreateAccount\x12\x18.pb.CreateAccountRequest\x1a\x19.pb.CreateAccountResponse\"M\x92A3\x12\x0eCreate account\x1a!Use this API to create an account\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/accounts\x12\x86\x01\n" +
	"\n" +
	"GetAccount\x12\x15.pb.GetAccountRequest\x1a\x16.pb.GetAccountResponse\"I\x92A-\x12\vGet account\x1a\x1eUse this API to get an account\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/accounts/{id}\x12\x88\x01\n" +
	"\fListAccounts\x12\x17.pb.ListAccountsRequest\x1a\x18.pb.ListAccountsResponse\"E\x92A.\x12\rList accounts\x1a\x1dUse this API to list accounts\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/accounts\x12\x98\x01\n" +
	"\x0eCreateTransfer\x12\x19.pb.CreateTransferRequest\x1a\x1a.pb.CreateTransferResponse\"O\x92A4\x12\x0fCreate transfer\x1a!Use this API to create a transfer\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/transfers\x12\xab\x01\n" +
	"\x10RenewAccessToken\x12\x1b.pb.RenewAccessTokenRequest\x1a\x1c.pb.RenewAccessTokenResponse\"\\\x92A8\x12\x12Renew access token\x1a\"Use this API to renew access token\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/users/renew_accessB{\x92AV\x12T\n" +
	"\x0fSimple Bank API\"<\n" +
	"\bAJack Ti\x12\x1ahttps://github.com/AJackTi\x1a\x14dtrong97vn@gmail.com2\x031.2Z github.com/AJackTi/simplebank/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),        // 0: pb.CreateUserRequest
	(*UpdateUserRequest)(nil),        // 1: pb.UpdateUserRequest
	(*LoginUserRequest)(nil),         // 2: pb.LoginUserRequest
	(*CreateAccountRequest)(nil),     // 3: pb.CreateAccountRequest
	(*GetAccountRequest)(nil),        // 4: pb.GetAccountRequest
	(*ListAccountsRequest)(nil),      // 5: pb.ListAccountsRequest
	(*CreateTransferRequest)(nil),    // 6: pb.CreateTransferRequest
	(*RenewAccessTokenRequest)(nil),  // 7: pb.RenewAccessTokenRequest
	(*CreateUserResponse)(nil),       // 8: pb.CreateUserResponse
	(*UpdateUserResponse)(nil),       // 9: pb.UpdateUserResponse
	(*LoginUserResponse)(nil),        // 10: pb.LoginUserResponse
	(*CreateAccountResponse)(nil),    // 11: pb.CreateAccountResponse
	(*GetAccountResponse)(nil),       // 12: pb.GetAccountResponse
	(*ListAccountsResponse)(nil),     // 13: pb.ListAccountsResponse
	(*CreateTransferResponse)(nil),   // 14: pb.CreateTransferResponse
	(*RenewAccessTokenResponse)(nil), // 15: pb.RenewAccessTokenResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0,  // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1,  // 1: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	2,  // 2: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	3,  // 3: pb.SimpleBank.CreateAccount:input_type -> pb.CreateAccountRequest
	4,  // 4: pb.SimpleBank.GetAccount:input_type -> pb.GetAccountRequest
	5,  // 5: pb.SimpleBank.ListAccounts:input_type -> pb.ListAccountsRequest
	6,  // 6: pb.SimpleBank.CreateTransfer:input_type -> pb.CreateTransferRequest
	7,  // 7: pb.SimpleBank.RenewAccessToken:input_type -> pb.RenewAccessTokenRequest
	8,  // 8: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	9,  // 9: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	10, // 10: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	11, // 11: pb.SimpleBank.CreateAccount:output_type -> pb.CreateAccountResponse
	12, // 12: pb.SimpleBank.GetAccount:output_type -> pb.GetAccountResponse
	13, // 13: pb.SimpleBank.ListAccounts:output_type -> pb.ListAccountsResponse
	14, // 14: pb.SimpleBank.CreateTransfer:output_type -> pb.CreateTransferResponse
	15, // 15: pb.SimpleBank.RenewAccessToken:output_type -> pb.RenewAccessTokenResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_create_account_proto_init()
	file_rpc_get_account_proto_init()
	file_rpc_list_accounts_proto_init()
	file_rpc_create_transfer_proto_init()
	file_rpc_renew_access_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
