name: ci-test

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:

      - name: Setup up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      
      - name: Run migrations
        uses: make migrateup

      - name: Test
        run: make test