name: ci-test

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Setup up Go 1.x
        users: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go
      
      - name: Check out code into the Go module directory
        users: actions/checkout@v2
      
      - name: Test
        run: make test